apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world
    image: yashvardhankukreja/hello-world
    ports:
    - containerPort: 3000

